coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 95%
        threshold: 2%

ignore:
  - "**/mock_*.go"
  - "**/testdata/**"
