= Comfy Gopher - Collections

image:https://codecov.io/gh/comfygopher/collections/graph/badge.svg?token=I5QQ2SU3E7[codecov,link=https://codecov.io/gh/comfygopher/collections]
image:https://img.shields.io/coderabbit/prs/github/comfygopher/collections?utm_source=oss&utm_medium=github&utm_campaign=comfygopher%2Fcollections&labelColor=5b5b5b&color=FF570A&link=https%3A%2F%2Fcoderabbit.ai&label=CodeRabbit+Reviews[CodeRabbit Pull Request Reviews]
image:https://goreportcard.com/badge/github.com/comfygopher/collections[Go Report Card,link=https://goreportcard.com/report/github.com/comfygopher/collections]

== What is Comfy Gopher?

*Comfy Gopher is a Set of general-purpose Tools, Utilities, and Data Structures for Comfortable Development*

These tools prioritize speed and ease of development over strict efficiency or full compliance with Go philosophy.
They accelerate development and enhance the experience, by reducing the cognitive load,
making them well suited for rapid prototyping.

== Comfy Gopher - Collections package

=== Goals

1. Provide convenient abstraction for collection data structures
1. Focus on developer experience
1. Reduce repetition in day-to-day collections operations
1. Address the missing ordered map data structure
1. Provide API for in-place modifications of collections
1. Reduce strain of juggling between empty slice pointers `[]V(nil) vs []V{}`

=== No-goals

This is a set of elements that the Collections package are NOT trying to achieve:

1. Thread-safety
+
You must implement your own thread-safety.

1. Superb efficiency
+
Although care is taken to ensure that the data structures used are efficient, exceptional efficiency is not the main goal here.

== Alternatives

There is a very nice library https://github.com/charbz/gophers[github.com/charbz/gophers].
Its API is a mix of mutable and immutable operations, which can be confusing.
Most of the methods there do return a new collection instance though. This has its applications,
but at the same time it presents some inconveniences when working with extensive amount of
other libraries that expect mutable elements.
